# Generated by Django 6.0.3 on 2026-05-02 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_rejection_reason_skillverificationrequest_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorshiprequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Skill Categories'},
        ),
        migrations.AlterModelOptions(
            name='skillverificationrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AlterModelOptions(
            name='verificationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='certificateproject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificateproject',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificateproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency_level',
            field=models.CharField(blank=True, choices=[('', 'Not Assigned'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='skill_proofs/'),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skillverificationrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='action',
            field=models.CharField(choices=[('mentorship_requested', 'Mentorship Requested'), ('mentorship_accepted', 'Mentorship Accepted'), ('mentorship_rejected', 'Mentorship Rejected'), ('verification_requested', 'Verification Requested'), ('skill_approved', 'Skill Approved'), ('skill_rejected', 'Skill Rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='accounts.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='skillverificationrequest',
            unique_together={('skill', 'student', 'teacher')},
        ),
        migrations.CreateModel(
            name='RecruiterShortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_candidates', to=settings.AUTH_USER_MODEL)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by_recruiters', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('recruiter', 'student_profile')},
            },
        ),
    ]
